// Generated by CoffeeScript 1.6.2
(function() {
  var Backend, DataSource, UserInterface,
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  UserInterface = (function() {
    var _this = this;

    function UserInterface() {
      var OTC,
        _this = this;

      OTC = new Backend();
      this.render('loginBox', 'mainTabs');
      OTC.bind('data.exchangeRates', this.updateContent.exchangeRates);
      OTC.requestData('exchangeRates');
      OTC.bind('login', function(data) {
        if (!data.success) {
          return console.log('login failed');
        } else {
          $('#login-box').dialog('close');
          return _this.updateContent.username(OTC.username);
        }
      });
    }

    UserInterface.prototype.renderSection = {
      loginBox: function() {
        $("#login-box").dialog({
          modal: true,
          autoOpen: true,
          dialogClass: 'no-close',
          closeOnEscape: false,
          draggable: false
        });
        $('#login-submit').button();
        return $('#login-form').submit(function(event) {
          event.preventDefault();
          return OTC.login($('#login-username').val(), $('#login-password').val());
        });
      },
      mainTabs: function() {
        return $('#main-tabs').tabs();
      }
    };

    UserInterface.prototype.render = function() {
      var section, sections, _i, _len, _results;

      sections = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = sections.length; _i < _len; _i++) {
        section = sections[_i];
        _results.push(this.renderSection[section]());
      }
      return _results;
    };

    UserInterface.prototype.updateContent = {
      exchangeRates: function(data) {
        var prop, val, _results;

        _results = [];
        for (prop in data) {
          val = data[prop];
          _results.push($('#exr-' + prop).text(val));
        }
        return _results;
      },
      username: function(data) {
        return $('#display-username').text(data);
      }
    };

    return UserInterface;

  }).call(this);

  Backend = (function() {
    function Backend() {
      this.trigger = __bind(this.trigger, this);
      this.bind = __bind(this.bind, this);
    }

    Backend.prototype.loggedIn = false;

    Backend.prototype.websocket = null;

    Backend.prototype.username = null;

    Backend.prototype._events = {};

    Backend.prototype.bind = function(event, f) {
      this._events[event] = this._events[event] || [];
      return this._events[event].push(f);
    };

    Backend.prototype.trigger = function(event, info) {
      var f, _i, _len, _ref, _results;

      if (!this._events[event]) {
        console.log("Unbound event: " + event);
        return;
      }
      _ref = this._events[event];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        _results.push(f(info));
      }
      return _results;
    };

    Backend.prototype.requestData = function(name) {
      if (DataSource[name]) {
        return this.trigger("data." + name, DataSource[name]);
      }
    };

    Backend.prototype.login = function(username, password) {
      if (!this.loggedIn) {
        this.username = username;
        return this.trigger('login', {
          success: true
        });
      }
    };

    return Backend;

  })();

  DataSource = {
    exchangeRates: {
      ask: 88.76000,
      bid: 87.18166,
      spread: 1.57834
    }
  };

  $(function() {
    return new UserInterface();
  });

}).call(this);
