// Generated by CoffeeScript 1.6.2
(function() {
  var OTC_BACKEND, OTC_UI, _OTC,
    __slice = [].slice;

  OTC_UI = (function() {
    var _this = this;

    function OTC_UI() {
      var OTC,
        _this = this;

      OTC = new _OTC();
      this.render('loginBox', 'mainTabs');
      OTC.events.bind('data.exchangeRates', this.updateContent.exchangeRates);
      OTC.requestData('exchangeRates');
      OTC.events.bind('login', function(data) {
        if (!data.success) {
          return console.log('login failed');
        } else {
          $('#login-box').dialog('close');
          return _this.updateContent.username(OTC.username);
        }
      });
    }

    OTC_UI.prototype.renderSection = {
      loginBox: function() {
        $("#login-box").dialog({
          modal: true,
          autoOpen: true,
          dialogClass: 'no-close',
          closeOnEscape: false,
          draggable: false
        });
        $('#login-submit').button();
        return $('#login-form').submit(function(event) {
          event.preventDefault();
          return OTC.login($('#login-username').val(), $('#login-password').val());
        });
      },
      mainTabs: function() {
        return $('#main-tabs').tabs();
      }
    };

    OTC_UI.prototype.render = function() {
      var section, sections, _i, _len, _results;

      sections = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = sections.length; _i < _len; _i++) {
        section = sections[_i];
        _results.push(this.renderSection[section]());
      }
      return _results;
    };

    OTC_UI.prototype.updateContent = {
      exchangeRates: function(data) {
        var prop, val, _results;

        _results = [];
        for (prop in data) {
          val = data[prop];
          _results.push($('#exr-' + prop).text(val));
        }
        return _results;
      },
      username: function(data) {
        return $('#display-username').text(data);
      }
    };

    return OTC_UI;

  }).call(this);

  _OTC = (function() {
    var _this = this;

    function _OTC() {}

    _OTC.prototype.loggedIn = false;

    _OTC.prototype.websocket = null;

    _OTC.prototype.username = null;

    /*
    Events management
    List of events that you can bind to:
    login: Fired when the server successfully logs
    data.*: Fired when data is received from the backend.
    */


    _OTC.prototype._events = {};

    _OTC.prototype.events = {
      bind: function(event, f) {
        _OTC._events[event] = _OTC._events[event] || [];
        return _OTC._events[event].push(f);
      },
      trigger: function(event, info) {
        var f, _i, _len, _ref, _results;

        if (!_OTC._events[event]) {
          console.log("Unbound event: " + event);
          return;
        }
        _ref = _OTC._events[event];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          _results.push(f(info));
        }
        return _results;
      }
    };

    _OTC.prototype.requestData = function(name) {
      if (OTC_BACKEND[name]) {
        return this.events.trigger("data." + name, OTC_BACKEND[name]);
      }
    };

    _OTC.prototype.login = function(username, password) {
      if (!this.loggedIn) {
        this.username = username;
        return this.events.trigger('login', {
          success: true
        });
      }
    };

    return _OTC;

  }).call(this);

  OTC_BACKEND = {
    exchangeRates: {
      ask: 88.76000,
      bid: 87.18166,
      spread: 1.57834
    }
  };

  $(function() {
    return new OTC_UI();
  });

}).call(this);
